### PR TITLE
Copy FAQ from wiki

### PR DESCRIPTION
**Pull request by mac-at-vaadin**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/designer-documentation/9)

### CODE REVIEW

**Comment by Peppe** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-faq.asciidoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmByJoIbWhCjnH5J8P:-KjmByJoIbWhCjnH5J8Q:b-8a6fbu) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L16)):*
> ```AsciiDoc
> == I have updated the Vaadin plugin, but I still can’t see the Designer.
> Even if you already have the Vaadin Plug-in for Eclipse installed, you will still have to Help->Install New Software. Select the vaadin.com/eclipse update site from the list, *and make sure Vaadin Designer is selected.*
> (Unfortunately Help ->Check for Updates *is not enough*, since Eclipse does not notice that new stuff is available.)
> ```

Add space between -> and Check

---

*[designer-faq.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmD-KtTdXfV44aobRs:-KjmD-KtTdXfV44aobRt:b-rfpmpi) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L101)):*
> ```AsciiDoc
> 
> == Related
> * https://vaadin.com/wiki?p_p_id=36&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&p_p_col_id=row-1&p_p_col_pos=2&p_p_col_count=4&_36_struts_action=%2Fwiki%2Fview&p_r_p_185834411_nodeName=vaadin.com+wiki&p_r_p_185834411_title=Installing+older+releases[Installing older releases]
> ```

Couldn't this short article be just embedded instead of relying on wiki in that part. It would be cleaner, and I don't know if we can rely on wiki in the long run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9)*

**Comment by mac-at-vaadin** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-faq.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmD-KtTdXfV44aobRs:-KjmDicZ9k_Xec0QxM7_:blbx9yy) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L101)):*
<details><summary><i>Previously, Peppe (Jens Jansson) wrote…</i></summary><blockquote>

Couldn't this short article be just embedded instead of relying on wiki in that part. It would be cleaner, and I don't know if we can rely on wiki in the long run.
</blockquote></details>

Sure, will just copy-paste it here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9)*

**Comment by mac-at-vaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-faq.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmD-KtTdXfV44aobRs:-KjmLtnNOOdCj-Mhx13x:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L101)):*
<details><summary><i>Previously, mac-at-vaadin (Maciej Przepióra) wrote…</i></summary><blockquote>

Sure, will just copy-paste it here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9)*

**Comment by mac-at-vaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-faq.asciidoc, line 16 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmByJoIbWhCjnH5J8P:-KjmMy-_-S5eMsDe7c2M:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L16)):*
<details><summary><i>Previously, Peppe (Jens Jansson) wrote…</i></summary><blockquote>

Add space between -> and Check
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9)*

**Comment by anssit** [comment]
Otherwise happy to lgtm but what do you think about the old versions section?

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-faq.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmD-KtTdXfV44aobRs:-KjmOEsSNlYwN79-Nmcl:bv1k9rv) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L101)):*
<details><summary><i>Previously, mac-at-vaadin (Maciej Przepióra) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, do we still want to keep this section? We don't have old versions available and the linked ones are rather ... old?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-:-KjmOOeLUZyW4L4iWQ5h:b-v9p86z)*

**Comment by mac-at-vaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-faq.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmD-KtTdXfV44aobRs:-KjmgpK0mGtcjZR82r0f:bsh12yy) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L101)):*
<details><summary><i>Previously, anssit wrote…</i></summary><blockquote>

Hmm, do we still want to keep this section? We don't have old versions available and the linked ones are rather ... old?
</blockquote></details>

I am just doing what @peppe suggested. Personally I think we could omit the versions list, but keep the instructions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9)*

**Comment by mac-at-vaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-faq.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmD-KtTdXfV44aobRs:-KjmhMMZ0SN29VZFTPGF:b-xtcxp) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L101)):*
<details><summary><i>Previously, mac-at-vaadin (Maciej Przepióra) wrote…</i></summary><blockquote>

I am just doing what @peppe suggested. Personally I think we could omit the versions list, but keep the instructions
</blockquote></details>

@Peppe could you comment on that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9)*

**Comment by Peppe** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[designer-faq.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmD-KtTdXfV44aobRs:-KjqQeiLSDxKskaoOBR-:b-3v27up) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L101)):*
<details><summary><i>Previously, mac-at-vaadin (Maciej Przepióra) wrote…</i></summary><blockquote>

@Peppe could you comment on that?
</blockquote></details>

I didn't look that much on the content, just that it is linking back to wiki which we wanted to remove in the first place. Anssi's comment is valid and linking to 0.x doesn't sound beneficial. Decide yourself best actions. Proposal sounds good. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9)*

**Comment by mac-at-vaadin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[designer-faq.asciidoc, line 101 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-KjmD-KtTdXfV44aobRs:-KjqgFsIDfrS6NX80MG-:bzi8kgn) ([raw file](https://github.com/vaadin/designer-documentation/blob/e01051579b36557c5010d04470add713cb1f28d5/designer-faq.asciidoc#L101)):*
<details><summary><i>Previously, Peppe (Jens Jansson) wrote…</i></summary><blockquote>

I didn't look that much on the content, just that it is linking back to wiki which we wanted to remove in the first place. Anssi's comment is valid and linking to 0.x doesn't sound beneficial. Decide yourself best actions. Proposal sounds good. 
</blockquote></details>

Updated – removed 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9)*

**Comment by anssit** [comment]
:lgtm: 

---

Reviewed 1 of 2 files at r3.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/9#-:-KjqykK4R-L6Kw_FMnOQ:bg7igkv)*

**Pull request merged**
