### PR TITLE
Add install instructions for IntelliJ IDEA

### PR DESCRIPTION
**Pull request by anssit**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/designer-documentation/5)

### CODE REVIEW

**Comment by anssit** [comment]
[Update Installation documentation (3)](https://trello.com/c/ZjP89hNP/1016-update-installation-documentation-3)

**Comment by Artur-** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-licensing.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4bVx7BoLpSsNUFuaf:-KV4bVx8suw1ZIDPiQPp:b6u4bdu) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L10)):*
>  the Vaadin Designer,
Vaadin Designer,

---

*[designer-licensing.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4bblPcneey_t4PMBB:-KV4bblPcneey_t4PMBC:b-jb75h0) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L14)):*
> Licence
License
(corrected in https://dev.vaadin.com/review/#/c/14652)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5)*

**Comment by szolo** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[designer-installing-idea.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4sWHlgh_ks2H1VM6h:-KV4sWHm2IVVvA_yOSti:bsdkwnu) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-installing-idea.asciidoc#L22)):*
> ```AsciiDoc
> . Open IntelliJ IDEA
> 
> . Choose [guilabel]#Preferences > Plugins#
> ```

In IntelliJ it's File menu -> Settings -> Plugins, not Preferences. At least in Windows :)

---

*[designer-installing-idea.asciidoc, line 36 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4u8ikQlahhvUsUqJ8:-KV4u8ilZQkdc-97ExF1:b-isj1xb) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-installing-idea.asciidoc#L36)):*
> ```AsciiDoc
> 
> If you want to remove Vaadin Designer from your IntelliJ IDEA installation, go to
> [guilabel]#Preferences > Plugins#, select [guilabel]#Vaadin Designer# from the list,
> ```

File menu -> Settings -> Plugins

---

*[designer-licensing.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4uM_gMqYK7WgnTM5h:-KV4uM_gMqYK7WgnTM5i:bt5kszh) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L14)):*
> ```AsciiDoc
> use the license included with your Pro Tools subscription. See
> <<dummy/../../framework/addons/addons-cval#addons.cval,"Installing Commercial
> Vaadin Add-on Licence">> for instructions for installing the license.
> ```

"**for** instructions **for** installing the license", should it be rephrased?

---

*[designer-licensing.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4ucL-v9gfYbiM_jBA:-KV4ucL031h49rNK3dX_:bexfh85) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L17)):*
> ```AsciiDoc
> 
> Please note that a separate license key is required for each developer. If you
> choose not input any license (even trial), you will be unable to save your work.
> ```

"choose not input" sounds confusing? Should it be "if you don't enter/input" or "choose not to input"?

---

*[designer-limitations.asciidoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4tCsqsiInHquksUwT:-KV4tCsrWKzcQ9Dk7-vu:b-iay2u1) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L12)):*
> ```AsciiDoc
> Limitations in Vaadin Designer 1.1:
> 
> * Custom widgetsets are not used when designing. 
> ```

Is it better to say "custom widgetsets are not supported"? Also doubts about "when" word, I'd use "while" here.

---

*[designer-limitations.asciidoc, line 13 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4tW89i_JuxljgPP2a:-KV4tW89i_JuxljgPP2b:b-cjn4wd) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L13)):*
> ```AsciiDoc
> 
> * Custom widgetsets are not used when designing. 
> * Custom (project) components and nested designs are shown as place-holders when designing.
> ```

Same here, in my opinion "rendered" was ok and again this "when designing"

---

*[designer-limitations.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4td_ErSEA3tWkyj7R:-KV4td_ErSEA3tWkyj7S:b3tdiv2) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L14)):*
> ```AsciiDoc
> * Custom widgetsets are not used when designing. 
> * Custom (project) components and nested designs are shown as place-holders when designing.
> * Limited support for GridLayout; no column- or row-spanning.
> ```

Should **:** be used after GridLayout, instead **;**?

---

*[designer-limitations.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4tpyykSXG15QKNC1D:-KV4tpyykSXG15QKNC1E:bhv7g23) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L15)):*
> ```AsciiDoc
> * Custom (project) components and nested designs are shown as place-holders when designing.
> * Limited support for GridLayout; no column- or row-spanning.
> * The declarative format does not currently support ClassResource (e.g for icons and images). 
> ```

I'd like to remove "currently" word here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5)*

**Comment by ripla** [comment]
Reviewed 8 of 10 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[designer-licensing.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV5D-H6062SFBu2KQs6:-KV5D-H6062SFBu2KQs7:bmp8jgb) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L17)):*
> ```AsciiDoc
> 
> Please note that a separate license key is required for each developer. If you
> choose not input any license (even trial), you will be unable to save your work.
> ```

Would remove `(even trial)`

---

*[designer-licensing.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV5CxPtTI3poEGAfdBt:-KV5CxPtTI3poEGAfdBu:b-eggobe) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L20)):*
> ```AsciiDoc
> 
> If you for any reason need to remove or change a valid license, it is located in
> [filename]#~/.vaadin.designer.developer.license#.
> ```

What about windows?

---

*[designer-limitations.asciidoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4tCsqsiInHquksUwT:-KV5D3nQg-epP6O9qgqS:byodfrj) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L12)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary>
> Is it better to say "custom widgetsets are not supported"? Also doubts about "when" word, I'd use "while" here.
</details>
Maybe just say `Custom client-side components are not supported when designing`

---

*[designer-limitations.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4tpyykSXG15QKNC1D:-KV5DNAbIRampyVo2wvl:bgxbog) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L15)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary>
> I'd like to remove "currently" word here.
</details>
`does not support ClassResource for loading resources such as icons or images`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5)*

**Comment by anssit** [comment]
Review status: 6 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[designer-installing-idea.asciidoc, line 22 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4sWHlgh_ks2H1VM6h:-KV9TeaEflu1fBU4tqGF:b-rph3s2) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-installing-idea.asciidoc#L22)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary>
> In IntelliJ it's File menu -> Settings -> Plugins, not Preferences. At least in Windows :)
</details>
And linux it seems.. on osx is different. Will update, thanks for pointing out!

---

*[designer-installing-idea.asciidoc, line 36 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4u8ikQlahhvUsUqJ8:-KVAEIXEYC_1QavdNKj8:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-installing-idea.asciidoc#L36)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary>
> File menu -> Settings -> Plugins
</details>
Done.

---

*[designer-licensing.asciidoc, line 10 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4bVx7BoLpSsNUFuaf:-KVACkRDh_38s3hCASI_:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L10)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> >  the Vaadin Designer,
> Vaadin Designer,
</details>
Done.

---

*[designer-licensing.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4uM_gMqYK7WgnTM5h:-KV9PUEiEsXWSpS1eJvo:b2xivx2) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L14)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary>
> "**for** instructions **for** installing the license", should it be rephrased?
</details>
A bit clumsy but couldn't come up with a better way to say it without changing the meaning. Let's leave it like that ok?

---

*[designer-licensing.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4bblPcneey_t4PMBB:-KVAClTgWM6OtSHaArnx:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L14)):*
<details><summary><i>Previously, Artur- (Artur) wrote…</i></summary>
> > Licence
> License
> (corrected in https://dev.vaadin.com/review/#/c/14652)
</details>
Done.

---

*[designer-licensing.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4ucL-v9gfYbiM_jBA:-KV9PQvd38UZx7VZNkDk:b-vk5c0s) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L17)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary>
> "choose not input" sounds confusing? Should it be "if you don't enter/input" or "choose not to input"?
</details>
"to" added.

---

*[designer-licensing.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV5D-H6062SFBu2KQs6:-KVACmQ5SFHhuJTFP-yW:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L17)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary>
> Would remove `(even trial)`
</details>
Done.

---

*[designer-licensing.asciidoc, line 20 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV5CxPtTI3poEGAfdBt:-KVACnIoUr0H8mTdyQo_:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L20)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary>
> What about windows?
</details>
Done.

---

*[designer-limitations.asciidoc, line 12 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4tCsqsiInHquksUwT:-KVAD90rwFhmDzZdK2F_:b-s06k5k) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L12)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary>
> Maybe just say `Custom client-side components are not supported when designing`
</details>
Done. I think "when" is ok.

---

*[designer-limitations.asciidoc, line 13 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4tW89i_JuxljgPP2a:-KVADqYCKYCkydSopHfP:b-ji6rx5) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L13)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary>
> Same here, in my opinion "rendered" was ok and again this "when designing"
</details>
I'd keep "when designing" because it's really a design-time limitation only.

---

*[designer-limitations.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4td_ErSEA3tWkyj7R:-KVAE8XpsSY2JYgNM35F:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L14)):*
<details><summary><i>Previously, szolo (Stepan Zolotarev) wrote…</i></summary>
> Should **:** be used after GridLayout, instead **;**?
</details>
Done.

---

*[designer-limitations.asciidoc, line 15 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4tpyykSXG15QKNC1D:-KVAEHW6EWclVLa85OQR:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-limitations.asciidoc#L15)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary>
> `does not support ClassResource for loading resources such as icons or images`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5)*

**Comment by ripla** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[designer-installing-idea.asciidoc, line 25 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KVAJkzQWeb__8LsfSR-:-KVAJkzQWeb__8LsfSR0:b-kcmnno) ([raw file](https://github.com/vaadin/designer-documentation/blob/b04de8dbd2bce0d85844661edb35c795f4aab9bd/designer-installing-idea.asciidoc#L25)):*
> ```AsciiDoc
> in Windows and Linux.
> 
> . Browse Repositories
> ```

Maybe `Select` or `Click` `browse repositories`

---

*[designer-licensing.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4ucL-v9gfYbiM_jBA:-KVAKJl0EDexql3xlgO6:b-yubnxk) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L17)):*
<details><summary><i>Previously, anssit wrote…</i></summary>
> "to" added.
</details>
Maybe `input` -> `enter`, `any` -> `a` and `work` -> `design` ?

---

*[designer-limitations.asciidoc, line 13 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KVAKjdtpjJTWK6mY0x_:-KVAKjdtpjJTWK6mY0xa:b-phnt17) ([raw file](https://github.com/vaadin/designer-documentation/blob/b04de8dbd2bce0d85844661edb35c795f4aab9bd/designer-limitations.asciidoc#L13)):*
> ```AsciiDoc
> 
> * Custom client-side components are not supported when designing. 
> * Custom (project) components and nested designs are rendered as place-holders in the designer.
> ```

Should `desiger` be uppercase?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5)*

**Comment by anssit** [comment]
Review status: 6 of 9 files reviewed at latest revision, 12 unresolved discussions.

---

*[designer-installing-idea.asciidoc, line 25 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KVAJkzQWeb__8LsfSR-:-KVAWeKL_RKLc_9JMER-:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/b04de8dbd2bce0d85844661edb35c795f4aab9bd/designer-installing-idea.asciidoc#L25)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary>
> Maybe `Select` or `Click` `browse repositories`
</details>
Done.

---

*[designer-licensing.asciidoc, line 17 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4ucL-v9gfYbiM_jBA:-KVAWnBaASSqsdptCZ8P:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L17)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary>
> Maybe `input` -> `enter`, `any` -> `a` and `work` -> `design` ?
</details>
Done.

---

*[designer-limitations.asciidoc, line 13 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KVAKjdtpjJTWK6mY0x_:-KVAWtFcu7J_iHhdUPNP:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/b04de8dbd2bce0d85844661edb35c795f4aab9bd/designer-limitations.asciidoc#L13)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary>
> Should `desiger` be uppercase?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5)*

**Comment by szolo** [comment]
:lgtm_strong: 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-:-KVAkBC443wjQQtH0qe3:b-uwkowd)*

**Comment by Artur-** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[designer-licensing.asciidoc, line 14 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-KV4uM_gMqYK7WgnTM5h:-KVAn8Qegn8kjmZURtuH:b8n8fl6) ([raw file](https://github.com/vaadin/designer-documentation/blob/8c432028de7ba62590f50332f9269b6b612eaa32/designer-licensing.asciidoc#L14)):*
<details><summary><i>Previously, anssit wrote…</i></summary>
> A bit clumsy but couldn't come up with a better way to say it without changing the meaning. Let's leave it like that ok?
</details>
Or say "for instructions on how to install"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5)*

**Comment by ripla** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-:-KVFOWDV7AojIOmGB8zr:bnfp4nl)*

**Comment by szolo** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-:-KVPAE4Zd7eVkrhKi7hK:b-uwkowd)*

**Comment by ripla** [comment]
:lgtm:

---

Reviewed 1 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/5#-:-KVPUKcwWkElCbF2yBsz:bnfp4nl)*

**Pull request merged**
