### PR TITLE
Add a chapter about templates. Fixes DES-93.

### PR DESCRIPTION
**Pull request by anssit**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/designer-documentation/6)

### CODE REVIEW

**Comment by johannesh2** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[designer-templates.asciidoc, line 26 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZVapNkheiAB9RQUISZ:-KZVapNl2GD_JMAxdYPF:bn3nno8) ([raw file](https://github.com/vaadin/designer-documentation/blob/b661c9cb34dda1ce62b6cbc5c35f00cbec51b2d0/designer-templates.asciidoc#L26)):*
> ```AsciiDoc
> <<dummy/../../framework/application/application-declarative#application.declarative.syntax,
> "Vaadin declarative format">>, with some additional information. Each template defines
> a design in terms of components and layouts but they can also contain style information 
> ```

"but it can also" instead of "they can also"

---

*[designer-templates.asciidoc, line 58 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZVb4V_UaWijg9MXcDp:-KZVb4V_UaWijg9MXcDq:bfwas3j) ([raw file](https://github.com/vaadin/designer-documentation/blob/b661c9cb34dda1ce62b6cbc5c35f00cbec51b2d0/designer-templates.asciidoc#L58)):*
> ```AsciiDoc
> 
> When you create a new design, the New Design Wizard allows you to pick a template. 
> As options you have templates that shipped with Vaadin Designer and any templates
> ```

Maybe something like this instead? "You can choose a  built-in template or a template that you have installed yourself."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/6)*

**Comment by johannesh2** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-:-KZVdP88hLDIg4waaJxX:bnfp4nl)*

**Comment by ripla** [comment]
Tested, works. Just a few questions.

---

Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[designer-templates.asciidoc, line 18 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZaKoPT8vUhPPBQtpX6:-KZaKoPT8vUhPPBQtpX7:b7hctc9) ([raw file](https://github.com/vaadin/designer-documentation/blob/ea5b73e372acc21764f7e4e2949789a3d46f8d69/designer-templates.asciidoc#L18)):*
> ```AsciiDoc
> you can also add to the selection by installing templates created by you or others.
> 
> This chapter explains what templates are, how to use them and how to create and install new templates. 
> ```

"how to use them, and how to..."

---

*[designer-templates.asciidoc, line 92 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZaLuNmiI0NdRcowoY2:-KZaLuNmiI0NdRcowoY3:b97eimj) ([raw file](https://github.com/vaadin/designer-documentation/blob/ea5b73e372acc21764f7e4e2949789a3d46f8d69/designer-templates.asciidoc#L92)):*
> Now that you have successfully installed the templates,
> Vaadin Designer is be able to pick them up.
Could this paragraph work without this?

---

*[designer-templates.asciidoc, line 100 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZaM36Mquf5Uj7eYpko:-KZaM36Mquf5Uj7eYpkp:brdvzoi) ([raw file](https://github.com/vaadin/designer-documentation/blob/ea5b73e372acc21764f7e4e2949789a3d46f8d69/designer-templates.asciidoc#L100)):*
> It can be used as such.
Could this paragraph work without this?

---

*[designer-templates.asciidoc, line 103 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZaM7L45VLVVXXYUzrW:-KZaM7L45VLVVXXYUzrX:bkyoubz) ([raw file](https://github.com/vaadin/designer-documentation/blob/ea5b73e372acc21764f7e4e2949789a3d46f8d69/designer-templates.asciidoc#L103)):*
> <style>
Code formatting?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-:-KZaMB4Q0UrS6_Cnm15B:b-5tlu5q)*

**Comment by anssit** [comment]
Updated.

---

Review status: 5 of 6 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[designer-templates.asciidoc, line 26 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZVapNkheiAB9RQUISZ:-KZaPubf8TxB8gxCro5Y:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/b661c9cb34dda1ce62b6cbc5c35f00cbec51b2d0/designer-templates.asciidoc#L26)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

"but it can also" instead of "they can also"
</blockquote></details>

Done.

---

*[designer-templates.asciidoc, line 58 at r1](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZVb4V_UaWijg9MXcDp:-KZaPvzLI0j2-NPuz7Sg:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/b661c9cb34dda1ce62b6cbc5c35f00cbec51b2d0/designer-templates.asciidoc#L58)):*
<details><summary><i>Previously, johannesh2 (Johannes Häyry) wrote…</i></summary><blockquote>

Maybe something like this instead? "You can choose a  built-in template or a template that you have installed yourself."
</blockquote></details>

Done.

---

*[designer-templates.asciidoc, line 18 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZaKoPT8vUhPPBQtpX6:-KZaPt4Ng2Xrmj-lm9yx:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/ea5b73e372acc21764f7e4e2949789a3d46f8d69/designer-templates.asciidoc#L18)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

"how to use them, and how to..."
</blockquote></details>

Done.

---

*[designer-templates.asciidoc, line 92 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZaLuNmiI0NdRcowoY2:-KZaQ5g_tcjhOaNUdlzY:b-sf9jrl) ([raw file](https://github.com/vaadin/designer-documentation/blob/ea5b73e372acc21764f7e4e2949789a3d46f8d69/designer-templates.asciidoc#L92)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

> Now that you have successfully installed the templates,
> Vaadin Designer is be able to pick them up.
Could this paragraph work without this?
</blockquote></details>

Sure. FFS TLDR.

---

*[designer-templates.asciidoc, line 100 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZaM36Mquf5Uj7eYpko:-KZaQT5DsKKUDapB7FI6:b-sf9jrl) ([raw file](https://github.com/vaadin/designer-documentation/blob/ea5b73e372acc21764f7e4e2949789a3d46f8d69/designer-templates.asciidoc#L100)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

> It can be used as such.
Could this paragraph work without this?
</blockquote></details>

Sure. FFS TLDR.

---

*[designer-templates.asciidoc, line 103 at r2](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-KZaM7L45VLVVXXYUzrW:-KZaRnHHBybXEPUMGOCd:b-896fix) ([raw file](https://github.com/vaadin/designer-documentation/blob/ea5b73e372acc21764f7e4e2949789a3d46f8d69/designer-templates.asciidoc#L103)):*
<details><summary><i>Previously, ripla (Risto Yrjänä) wrote…</i></summary><blockquote>

> <style>
Code formatting?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-:-KZaT21meSKBV-3oBO9U:b-bw8e14)*

**Comment by ripla** [comment]
:lgtm_strong: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-:-KZaYCjgBHr5kVko6qa1:b-uwkowd)*

**Comment by johannesh2** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/designer-documentation/6#-:-KZaZ1ZFjRiJz5A-6wP8:bnfp4nl)*

**Pull request merged**
